#!/bin/sh

$_ZAP_FLAGS

yum install -y epel-release
yum install -y bash-completion


pushd "$_ZAP_FILES/$_ZAP_STAGE/"
reponame="ram-framework"

cat > "./${reponame}.repo" <<- EOF
	[${reponame}]
	name=${reponame}
	baseurl=file://$PWD/results/default/
	enabled=1
	gpgcheck=0
EOF

repopath="$(yum-config-manager --add-repo "./${reponame}.repo" | grep 'repo saved to' | cut -c15-)"

yum install -y ram-framework

rm -f "${repopath}"
popd


find /etc/sysconfig/network-scripts/ -name 'ifcfg-*' ! -name 'ifcfg-lo' -delete
